jadwal/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='jadwal'
urlpatterns = [
    path('create', views.create_jadwal, name="create"),
    path('', views.jadwal, name='jadwal'),
    path('delete', views.delete)
]

mainpage/urls.py
from django.urls import path
from . import views
#url for app
urlpatterns = [
    path('', views.home, name='home'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, re_path
from mainpage.views import home
from jadwal.views import jadwal

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^mainpage/', include('mainpage.urls')),
    re_path(r'^$', home, name='home'),
    re_path(r'^jadwal/', include('jadwal.urls')),
    re_path(r'^jadwal/jadwal.html', jadwal, name='jadwal')
]

jadwal/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Jadwal(models.Model):
    nama_kegiatan = models.CharField(max_length=50)
    tempat = models.CharField(max_length=25)
    kategori = models.CharField(null=True, max_length=25)
    tanggal = models.DateField(default=timezone.now)
    waktu = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.nama_kegiatan

mainpage/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from . import models
from django import forms
import datetime

class JadwalForm(forms.ModelForm):
        nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Nama Kegiatan",
                }))
        tempat = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Tempat",
                }))
        kategori = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Kategori",
                }))
        tanggal = forms.DateField(widget=forms.SelectDateWidget(attrs={
                "class" : "datefield jadwalfields",
                "required" : True,
                }), initial=datetime.datetime.now() )
        waktu = forms.TimeField(widget=forms.TimeInput(attrs={
                "class" : "datefield jadwalfields",
                "placeholder":"00:00",
                "required" : True,
                }), initial=datetime.datetime.now() ) 

        class Meta:
                model = models.Jadwal
                fields = ["nama_kegiatan", "kategori", "tempat", "tanggal", "waktu"]

jadwal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import JadwalForm
from .models import Jadwal
from django.utils import timezone
import datetime

# Create your views here.
def create_jadwal(request):
    form = JadwalForm()
    if request.method =="POST":
        form = JadwalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('jadwal')
    return render(request, "form.html", {'form':form})

def jadwal(request):
    jadwals = Jadwal.objects.order_by("tanggal", "waktu")
    response = {
        'jadwal' : jadwals
    }
    return render(request, "jadwal.html", response)

def delete(request):
    if request.method == "POST":
        id = request.POST['id']
        Jadwal.objects.get(id=id).delete()
    return redirect('jadwal')

mainpage/views.py
from django.shortcuts import render
# https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_theme_me_complete&stacked=h
# Create your views here.
def home(request):
    return render(request, 'index.html')

jadwal/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet"  href="{% static 'css/style5.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
    <title>Bikin Jadwal</title>
</head>
<body class="form-body">
    <div class="form-cont">
        <h2>Add Jadwal</h2>
        <form method="POST" action="{% url 'jadwal:create' %}" class="form">
            {% csrf_token %}
            <p>Nama Kegiatan</p>
            {{ form.nama_kegiatan }}
            <p>Tempat</p>
            {{ form.tempat }}
            <p>Kategori</p>
            {{ form.kategori }}
            <p>Waktu & Tanggal</p>
            <p>
                {{ form.tanggal }}
                {{ form.waktu }}
            </p>
            <div class="full">
                <a href="{% url 'jadwal:jadwal' %}"><button type="button" class="button delete">Back</button></a>
                <input type="Submit" class="button" value="Submit" />
            </div>
        </form>
    </div>
</body>
</html>

jadwal/templates/jadwal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet"  href="{% static 'css/style5.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
    <title>Bikin Jadwal</title>
</head>
<body>
    <div class="container">
        <h1>Jadwal Ku</h1>
        <div class="flex">
            <p>Today - {{ server_time }}</p>
            <a href="create">
                <button class="button">Create Jadwal</button>
            </a>
        </div>
        {% for j in jadwal %}
            <div class="jadwal-card">
                <h2><span>{{ j.kategori }}</span> - {{ j.nama_kegiatan }}</h2>
                <div class="flex">
                    <div>
                        <h4>di {{ j.tempat }}</h4>
                        <p>{{ j.tanggal }} - {{ j.waktu }}</p>
                    </div>
                    <form action="delete" method="POST" >
                        {% csrf_token %}
                        <input type="hidden" value="{{ j.id }}" name="id" />
                        <input class="button delete" type="submit" value="Delete" />
                    </form>
                </div>
            </div>
        {% endfor %}

    </div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Profile diri</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/story3-stev.css' %}">
</head> 
<body id="top">
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top" style="background-color: #050505;">
        <a class="navbar-brand" href="#">
            <img src="{% static "img/logo_transparent.png" %}" width="40" height="40" alt="logo ppw">
        </a>
        <ul class="navbar-nav navbar-center ml-auto">
            <li class="nav-item navbutton-right">
                <a class="nav-link" href="#about">About</a>
            </li>
            <li class="nav-item navbutton-right">
                <a class="nav-link" href="#resume">Resume</a>
            </li>
            <li class="nav-item navbutton-right">
                <a class="nav-link" href="#contact">Contact</a>
            </li>
	    <li class="nav-item navbutton-right">
                <a class="nav-link" href="{% url 'jadwal' %}">Schedule</a>
            </li>
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</body>
    <script src="{% static 'jquery-3.3.1.slim.js' %}"></script>
    <script src="{% static bootstrap.bundle.min.js %}"></script>
    {% block jquery %}
    {% endblock %}
</html>